<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodelSpringGenerator" nsURI="http://metamodelSpringGenerator"
    nsPrefix="metamodelSpringGenerator">
  <eClassifiers xsi:type="ecore:EClass" name="App">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtos" upperBound="-1" eType="#//DTO"
        containment="true" eOpposite="#//DTO/app"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true" eOpposite="#//Controller/app"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app" lowerBound="1" eType="#//App"
        eOpposite="#//App/dtos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true" eOpposite="#//Attribute/dto"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dto" lowerBound="1" eType="#//DTO"
        eOpposite="#//DTO/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributetype" lowerBound="1"
        eType="#//AttributeType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="String"/>
    <eLiterals name="Integer" value="1"/>
    <eLiterals name="Double" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveType" eType="#//PrimitiveType"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dto" eType="#//DTO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAttributeType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListAttributeType" eSuperTypes="#//AttributeType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EReference" name="app" lowerBound="1" eType="#//App"
        eOpposite="#//App/controllers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoints" upperBound="-1"
        eType="#//Endpoint" containment="true" eOpposite="#//Endpoint/controller"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathpart" upperBound="-1"
        eType="#//PathPart" containment="true" eOpposite="#//PathPart/controller"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" lowerBound="1"
        eType="#//Controller" eOpposite="#//Controller/endpoints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathpart" upperBound="-1"
        eType="#//PathPart" containment="true" eOpposite="#//PathPart/endpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputBody" eType="#//DTO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputBody" eType="#//DTO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="#//HttpMethod" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableType" eType="#//PrimitiveType"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//Controller"
        eOpposite="#//Controller/pathpart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" eType="#//Endpoint"
        eOpposite="#//Endpoint/pathpart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethod">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
    <eLiterals name="PATCH" value="4"/>
  </eClassifiers>
</ecore:EPackage>
